export const FETCH_CITIES_REQUEST='FETCH_CITIES_REQUEST'
export const FETCH_CITIES_SUCCESS='FETCH_CITIES_SUCCESS'
export const FETCH_CITIES_FAIL='FETCH_CITIES_FAIL'

export const SHOW_CITY_REQUEST = 'SHOW_CITY_REQUEST';
export const SHOW_CITY_SUCCESS = 'SHOW_CITY_SUCCESS';
export const SHOW_CITY_FAIL = 'SHOW_CITY_FAIL';


export const ADD_CITY_REQUEST = 'ADD_CITY_REQUEST';
export const ADD_CITY_SUCCESS = 'ADD_CITY_SUCCESS';
export const ADD_CITY_FAIL = 'ADD_CITY_FAIL';

export const EDIT_CITY_REQUEST = 'EDIT_CITY_REQUEST';
export const EDIT_CITY_SUCCESS = 'EDIT_CITY_SUCCESS';
export const EDIT_CITY_FAIL = 'EDIT_CITY_FAIL';

export const DELETE_CITY_REQUEST = 'DELETE_CITY_REQUEST';
export const DELETE_CITY_SUCCESS = 'DELETE_CITY_SUCCESS';
export const DELETE_CITY_FAIL = 'DELETE_CITY_FAIL';
