// routesConstants.js
export const FETCH_ROUTES_REQUEST = 'FETCH_ROUTES_REQUEST';
export const FETCH_ROUTES_SUCCESS = 'FETCH_ROUTES_SUCCESS';
export const FETCH_ROUTES_FAIL = 'FETCH_ROUTES_FAIL';

export const ADD_ROUTE_REQUEST = 'ADD_ROUTE_REQUEST';
export const ADD_ROUTE_SUCCESS = 'ADD_ROUTE_SUCCESS';
export const ADD_ROUTE_FAIL = 'ADD_ROUTE_FAIL';

export const EDIT_ROUTE_REQUEST = 'EDIT_ROUTE_REQUEST';
export const EDIT_ROUTE_SUCCESS = 'EDIT_ROUTE_SUCCESS';
export const EDIT_ROUTE_FAIL = 'EDIT_ROUTE_FAIL';

export const DELETE_ROUTE_REQUEST = 'DELETE_ROUTE_REQUEST';
export const DELETE_ROUTE_SUCCESS = 'DELETE_ROUTE_SUCCESS';
export const DELETE_ROUTE_FAIL = 'DELETE_ROUTE_FAIL';

export const SHOW_ROUTE_REQUEST = 'SHOW_ROUTE_REQUEST';
export const SHOW_ROUTE_SUCCESS = 'SHOW_ROUTE_SUCCESS';
export const SHOW_ROUTE_FAIL = 'SHOW_ROUTE_FAIL';