// stationsConstants.js
export const FETCH_STATIONS_REQUEST = 'FETCH_STATIONS_REQUEST';
export const FETCH_STATIONS_SUCCESS = 'FETCH_STATIONS_SUCCESS';
export const FETCH_STATIONS_FAIL = 'FETCH_STATIONS_FAIL';

export const ADD_STATION_REQUEST = 'ADD_STATION_REQUEST';
export const ADD_STATION_SUCCESS = 'ADD_STATION_SUCCESS';
export const ADD_STATION_FAIL = 'ADD_STATION_FAIL';

export const EDIT_STATION_REQUEST = 'EDIT_STATION_REQUEST';
export const EDIT_STATION_SUCCESS = 'EDIT_STATION_SUCCESS';
export const EDIT_STATION_FAIL = 'EDIT_STATION_FAIL';

export const DELETE_STATION_REQUEST = 'DELETE_STATION_REQUEST';
export const DELETE_STATION_SUCCESS = 'DELETE_STATION_SUCCESS';
export const DELETE_STATION_FAIL = 'DELETE_STATION_FAIL';

export const SHOW_STATION_REQUEST = 'SHOW_STATION_REQUEST';
export const SHOW_STATION_SUCCESS = 'SHOW_STATION_SUCCESS';
export const SHOW_STATION_FAIL = 'SHOW_STATION_FAIL';