// tripsConstants.js
export const FETCH_TRIPS_REQUEST = 'FETCH_TRIPS_REQUEST';
export const FETCH_TRIPS_SUCCESS = 'FETCH_TRIPS_SUCCESS';
export const FETCH_TRIPS_FAIL = 'FETCH_TRIPS_FAIL';

export const ADD_TRIP_REQUEST = 'ADD_TRIP_REQUEST';
export const ADD_TRIP_SUCCESS = 'ADD_TRIP_SUCCESS';
export const ADD_TRIP_FAIL = 'ADD_TRIP_FAIL';

export const EDIT_TRIP_REQUEST = 'EDIT_TRIP_REQUEST';
export const EDIT_TRIP_SUCCESS = 'EDIT_TRIP_SUCCESS';
export const EDIT_TRIP_FAIL = 'EDIT_TRIP_FAIL';

export const DELETE_TRIP_REQUEST = 'DELETE_TRIP_REQUEST';
export const DELETE_TRIP_SUCCESS = 'DELETE_TRIP_SUCCESS';
export const DELETE_TRIP_FAIL = 'DELETE_TRIP_FAIL';

export const SHOW_TRIP_REQUEST = 'SHOW_TRIP_REQUEST';
export const SHOW_TRIP_SUCCESS = 'SHOW_TRIP_SUCCESS';
export const SHOW_TRIP_FAIL = 'SHOW_TRIP_FAIL';